### ISSUE TITLE
Functions vs. methods

### ISSUE THREAD

**Issue by Lecrapouille** [Reedbeta/reed-util#5]
Hi, not an issue but a design question concerning your vector classes: why did you choose functions rather than methods ? For example:
foo5 = normalize(foo5);
Instead of:
foo5.normalize();

Thx !

**Comment by Reedbeta** [comment]
Hi Lecrapouille, mostly I just prefer free functions for this, as a personal style choice.

One reason is that with methods, it's not very clear whether they act on the vector in-place, or they return a new vector. For instance, with `foo5.normalize()`, is that a `void` method that modifies `foo5`, or does it construct a new vector and return it, leaving `foo5` unchanged? It's hard to remember.

In contrast, `normalize(foo5)` is pretty clearly constructing a new vector, IMO. It would be very strange for a function call like that to modify its argument in-place.

Another thing, though this is more debatable, is applying functions to more complicated expressions. I think that

    foo = normalize(bar * coo * 0.5 + doodad / gewgaw);

looks more readable than

    foo = (bar * coo * 0.5 + doodad / gewgaw).normalize();

**Comment by Lecrapouille** [comment]
Ok, your arguments sound nice (and I missed this part on your blog) ! Thanks for your reply.
